/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import Utility.KonversiAngka;
import Utility.autonumber;
import Utility.autonumbertransaksi;
import Utility.cetak;
import Utility.koneksi;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;  

/**
 *
 * @author User
 */
public class BarangMasuk extends javax.swing.JFrame  {
static koneksi coon= new koneksi();

    autonumbertransaksi auto=new autonumbertransaksi();
static DefaultTableModel tb;
       SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
 SimpleDateFormat tahun = new SimpleDateFormat("yy");
 SimpleDateFormat bulan = new SimpleDateFormat("MM"); 
    KonversiAngka konver;
   NumberFormat kurensi = NumberFormat.getInstance();
    cetak Cetak=new cetak();
 int tottal;
 boolean tab;
    /**
     * Creates new form BarangMasuk
     */
    public BarangMasuk() {
        initComponents();
        jDateChooser1.setDate(new Date());
        setLocationRelativeTo(this);
         new tbl_model().tabelmodel();
          Setkodeaset();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtkodetr = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton2.setText("Simpan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("+");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton3KeyReleased(evt);
            }
        });

        jButton4.setText("-");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Kode");

        txtkodetr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkodetrActionPerformed(evt);
            }
        });
        txtkodetr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtkodetrKeyReleased(evt);
            }
        });

        jLabel3.setText("Tanggal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtkodetr, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtkodetr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Nama");

        jLabel6.setText("Kode Barang");

        jButton5.setText("...");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton5KeyReleased(evt);
            }
        });

        jLabel4.setText("Satuan");

        txtsatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsatuanActionPerformed(evt);
            }
        });

        jLabel5.setText("Qty");

        txtqty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqtyActionPerformed(evt);
            }
        });
        txtqty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtqtyKeyReleased(evt);
            }
        });

        jLabel7.setText("Harga");

        txtharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargaActionPerformed(evt);
            }
        });

        jLabel8.setText("Stock");

        txtstock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtkodebr, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtsatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(10, 10, 10)
                        .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtqty, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(10, 10, 10)
                        .addComponent(txtstock, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(273, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(txtkodebr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5)
                    .addComponent(jLabel4)
                    .addComponent(txtsatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5)
                    .addComponent(txtstock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setText("Total");

        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });

        jLabel10.setText("Terbilang");

        txterbilang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txterbilangActionPerformed(evt);
            }
        });

        jButton1.setText("Edit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txttotal)
                    .addComponent(txterbilang))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txterbilang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtsatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsatuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsatuanActionPerformed

    private void txtqtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtqtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtqtyActionPerformed

    private void txtkodetrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkodetrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkodetrActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
          int baris=jTable1.getSelectedRow();
          if (baris<0) {
              JOptionPane.showMessageDialog(rootPane,"Pilih Data Yang Ingin Dihapus Terlebih Dahulu !!!");
        }
          else{
                      tb.removeRow(baris);
        total();
          }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
           if (txtkodetr.getText().equals("")||jTable1.getRowCount()==0) {
        JOptionPane.showMessageDialog(this,"Data belum lengkap !!!");
    }
    else{
               if (cek()) {
                   retur();
                   simpanedit();
                   simpanedit2();
                   simpanUbah(); 
               }
               else{
        simpan();
        simpan2();
        simpanUbah();
        
               }
        bersihbr();
        Setkodeaset();
            new tbl_model().tabelmodel();
        JOptionPane.showMessageDialog(rootPane,"Data Telah Tersimpan");
        }
           
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
 
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txthargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargaActionPerformed

    private void txtstockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstockActionPerformed

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalActionPerformed

    private void txterbilangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txterbilangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txterbilangActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
edit();
total();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtkodetrKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtkodetrKeyReleased
tampilbeli();
    }//GEN-LAST:event_txtkodetrKeyReleased

    private void txtqtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtqtyKeyReleased
        // TODO add your handling code here:
           if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            jButton3.requestFocus();
        }
    }//GEN-LAST:event_txtqtyKeyReleased

    private void jButton3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyReleased
        // TODO add your handling code here:
           if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
               if (txtqty.getText().equals("")) {
            
              JOptionPane.showMessageDialog(rootPane,"Masukan Qty Barang !!!");
        }
        else if (cekbarang()) {
            JOptionPane.showMessageDialog(rootPane,"Barang Sudah DiInput");
        }
        else{
            int sub,qty,harga;
            qty=Integer.valueOf(txtqty.getText());
            harga=Integer.valueOf(txtharga.getText());
            sub=qty*harga;
  tb.addRow(new Object[]{txtkodebr.getText(),txtnama.getText(),txtsatuan.getText(),txtqty.getText(),txtharga.getText(),sub,null});
        jTable1.setModel(tb);
        bersihbr();
        total();
        }
     jButton5.requestFocus();
        }
    }//GEN-LAST:event_jButton3KeyReleased

    private void jButton5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton5KeyReleased
        // TODO add your handling code here:
             if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
           new cariBarangjmasuk().setVisible(true);
        }
    }//GEN-LAST:event_jButton5KeyReleased

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
           new cariBarangjmasuk().setVisible(true);
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
         if (txtqty.getText().equals("")) {
            
              JOptionPane.showMessageDialog(rootPane,"Masukan Qty Barang !!!");
        }
        else if (cekbarang()) {
            JOptionPane.showMessageDialog(rootPane,"Barang Sudah DiInput");
        }
        else{
            int sub,qty,harga;
            qty=Integer.valueOf(txtqty.getText());
            harga=Integer.valueOf(txtharga.getText());
            sub=qty*harga;
  tb.addRow(new Object[]{txtkodebr.getText(),txtnama.getText(),txtsatuan.getText(),txtqty.getText(),txtharga.getText(),sub,null});
        jTable1.setModel(tb);
        bersihbr();
        total();
        }
         jButton5.requestFocus();
    }//GEN-LAST:event_jButton3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BarangMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BarangMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BarangMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BarangMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BarangMasuk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTable1;
    public static final javax.swing.JTextField txterbilang = new javax.swing.JTextField();
    public static final javax.swing.JTextField txtharga = new javax.swing.JTextField();
    public static final javax.swing.JTextField txtkodebr = new javax.swing.JTextField();
    private javax.swing.JTextField txtkodetr;
    public static final javax.swing.JTextField txtnama = new javax.swing.JTextField();
    public static final javax.swing.JTextField txtqty = new javax.swing.JTextField();
    public static final javax.swing.JTextField txtsatuan = new javax.swing.JTextField();
    public static final javax.swing.JTextField txtstock = new javax.swing.JTextField();
    public static final javax.swing.JTextField txttotal = new javax.swing.JTextField();
    // End of variables declaration//GEN-END:variables
    public static class tbl_model{
    public void tabelmodel(){
       tb =new DefaultTableModel(){

           @Override
           public Class getColumnClass(int columnIndex) {
               switch (columnIndex){
            case 6 :
                return Boolean.class;
                default :
                return String.class;
        }
           }
         
       };
       tb.addColumn("Kode Bar4ng ");
       tb.addColumn("Nama Barang ");
       tb.addColumn("Satuan");
       tb.addColumn("Qty");
       tb.addColumn("Harga");
       tb.addColumn("Sub Total");
       tb.addColumn("Ubah Harga");
        jTable1.setModel(tb);
       
    }
    }
  void bersihbr(){
      txtkodebr.setText("");
      txtnama.setText("");
      txtsatuan.setText("");
      txtqty.setText("");
      txtharga.setText("");
      txtstock.setText("");
      txttotal.setText("");
      txterbilang.setText("");
  }
  void simpan2(){
     for (int i = 0; i < jTable1.getRowCount()  ; i++) {  
                coon.simpanData("insert into tbl_detilmasuk	values"
                + "	('"+txtkodetr.getText()+"'," 
                + "'"+jTable1.getValueAt(i , 0).toString()+"',"
                + "'"+jTable1.getValueAt(i , 3).toString()+"',"
                + "'"+jTable1.getValueAt(i , 4).toString()+"',"
                + "'"+jTable1.getValueAt(i , 5).toString()+"');");
                    	 
        }
}
    void simpanedit2(){
     for (int i = 0; i < jTable1.getRowCount()  ; i++) {  
                coon.simpanData("  update tbl_detilmasuk	set " 
                + "qty='"+jTable1.getValueAt(i , 3).toString()+"',"
                + "harga= '"+jTable1.getValueAt(i , 4).toString()+"',"
                + "sub='"+jTable1.getValueAt(i , 5).toString()+"'"
                        + "where"
                        + " KodeTransaksi='"+txtkodetr.getText()+"' and "
                        + "KodeBarang='"+jTable1.getValueAt(i , 0).toString()+"'");
                    	 
        }
}
     void simpanedit (){ 
                coon.simpanData("  update tbl_masuk	set "  
                + "total='"+txttotal.getText()+"'"
                        + "where"
                        + " KodeTransaksi='"+txtkodetr.getText()+"' " );
                    	 
         
}
  void simpanUbah(){
       for (int i = 0; i < jTable1.getRowCount()  ; i++) {  
          if (jTable1.getValueAt(i, 6)==null ) {
              
          }
          
         else if ( (boolean)jTable1.getValueAt(i, 6)==true) {
                coon.simpanData("insert into ubahharga	values"
                + "	('"+jTable1.getValueAt(i , 0).toString()+"',"  
                + "'"+jTable1.getValueAt(i , 4).toString()+"');");
           }
          
               
                    	 
        }
       
  }
  void simpan(){
     
coon.simpanData("insert into tbl_masuk	values"
                + "	('"+txtkodetr.getText()+"'," 
                + "'"+sdf.format(jDateChooser1.getDate())+"',"
                + "'"+txttotal.getText()+"');");
       
                  
   }
   public void Setkodeaset(){
        try {          
             String kode="/"+bulan.format(jDateChooser1.getDate())+"/"+tahun.format(jDateChooser1.getDate());
     auto.SetAutoNumber("tbl_masuk","KodeTransaksi",kode); 
     txtkodetr.setText(auto.GetAutoNumber());    
        } catch (Exception e) {
       System.out.printf(null, e);
        }
  }
   void edit(){
       int a,b,c;
           for (int i = 0; i < jTable1.getRowCount()  ; i++) { 
             a=Integer.valueOf(jTable1.getValueAt(i, 3).toString());  
             b=Integer.valueOf(jTable1.getValueAt(i, 4).toString());  
             c=a*b;
             jTable1.setValueAt(c, i, 5);
           }
   }
 public void total(){ 
tottal=0;
       for (int i = 0; i < jTable1.getRowCount()  ; i++) {  
    	tottal=tottal+Integer.valueOf(jTable1.getValueAt(i , 5).toString());
       } 
 txttotal.setText(""+tottal); 
 konver=new KonversiAngka(tottal); 
 txterbilang.setText(konver.getText());
 
}
void tampilbeli(){
    
         new tbl_model().tabelmodel();
         bersihbr(); 
    try {
        // TODO add your handling code here:
        ResultSet res = coon.ambilData("select *from vbeli where KodeTransaksi='"+txtkodetr.getText()+"'");
        while (res.next()){
            txtkodetr.setText(res.getString(1)); 
            jDateChooser1.setDate(res.getDate(2));
            txttotal.setText(res.getString(10));
             tb.addRow(new Object[]{res.getString(3),res.getString(4),res.getString(5)
                    ,res.getString(6),res.getString(7),res.getString(8)}); 
 konver=new KonversiAngka(res.getInt(10)); 
 txterbilang.setText(konver.getText());
        }
         } catch (SQLException ex) {
       Logger.getLogger(Penjualan.class.getName()).log(Level.SEVERE, null, ex);
    }
}
 boolean cek(){
     boolean i = false;
        ResultSet res = coon.ambilData("select *from vbeli where KodeTransaksi='"+txtkodetr.getText()+"'");
    try {
        if (res.next()) {
            
        i=true;
        }
        else{
            i=false;
        }
    } catch (SQLException ex) {
        Logger.getLogger(BarangMasuk.class.getName()).log(Level.SEVERE, null, ex);
    }
    return i;
}
void retur(){
      for (int i = 0; i < jTable1.getRowCount()  ; i++) {  
              try {
                  int qtyretur,qtyjual,selisih;
                 
                  ResultSet res = coon.ambilData("select * from tbl_detilmasuk where KodeTransaksi='"+txtkodetr.getText()+"' and KodeBarang='"
                          +jTable1.getValueAt(i , 0).toString()+"'" );
                  res.next(); 
                        qtyjual=res.getInt(3);
                        qtyretur=Integer.valueOf(jTable1.getValueAt(i , 3).toString());
                        selisih=qtyjual-qtyretur;  
                    coon.simpanData("update tblbarang  set "
                + "qty = qty-"+selisih+""  
                + " where " 
                + "Kode  = '"+jTable1.getValueAt(i , 0).toString()+"'");
                     
                 
              } catch (SQLException ex) {
                  Logger.getLogger(Penjualan.class.getName()).log(Level.SEVERE, null, ex);
              }
        
          }
}
boolean cekbarang(){
    boolean e =false;
    for (int i = 0; i < jTable1.getRowCount()  ; i++) {
             if (txtkodebr.getText().equals(jTable1.getValueAt(i, 0).toString())) { 
               e=true;
             }
             else{
             e =false;
             }
    }
    return e;
    }
void shortvut(java.awt.event.KeyEvent evt){
      if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            jButton3.requestFocus();
        }
}}
