/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import Utility.KonversiAngka;
import Utility.autonumber;
import Utility.cetak;
import Utility.koneksi;
import java.awt.Color;
import java.awt.Component;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
/**
 *
 * @author User
 */
public class DataPenjualan extends javax.swing.JFrame {
DefaultTableModel tb; 

      koneksi coon=new koneksi(); 
   static SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    autonumber auto=new autonumber();
   NumberFormat kurensi = NumberFormat.getInstance();
    cetak Cetak=new cetak();
 int tottal;
 boolean tab;
 
    /**
     * Creates new form DataPenjualan
     */
    public DataPenjualan() {
        initComponents();
        tabelmodel();
        total();
         jTable1.setDefaultRenderer(Object.class,new  mytablecellrender());  
        setExtendedState(MAXIMIZED_BOTH); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Tanggal Awal");

        jLabel2.setText("Tanggal Akhir");

        jLabel3.setText("Total Omset");

        jButton1.setText("tampil");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 835, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:d
        if (jDateChooser1.getDate()==null||jDateChooser2.getDate()==null) {
            JOptionPane.showMessageDialog(rootPane, "Pilih Tanggal Terlebih Dahulu !!");
        }
        else{
        tabelmodelpertanggal();
        total();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataPenjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
     static class mytablecellrender extends DefaultTableCellRenderer{
String tgl=""+sdf.format(new Date());
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
         Component c= super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column); //To change body of generated methods, choose Tools | Templates.
                    if ( table.getModel().getValueAt(row, 2).equals(tgl)) { 
                   c.setBackground(  Color.red );  
                        }
                    else if (row==table.getSelectedRow()) {
                  c.setBackground(  Color.LIGHT_GRAY );  
            }
                        else{
                            
                    c.setBackground(  table.getBackground() );
                        }
                    c.setForeground(Color.BLACK);
                    
     
             return this;
        }
        
    } 
    public void tabelmodel(){
       tb =new DefaultTableModel();
       tb.addColumn("No Faktu");
       tb.addColumn("Tanggal");
       tb.addColumn("Tempo"); 
       tb.addColumn("Nama Otlet");
       tb.addColumn("Nama Barang");
       tb.addColumn("Qty");
       tb.addColumn("Harga");
       tb.addColumn("Disc");
       tb.addColumn("Bonus");
       tb.addColumn("Subtotal");
       try {
           
   
         ResultSet res = coon.ambilData("select *from vpenjualan");
        while (res.next()){
                    tb.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3)
                    ,res.getString(5),res.getString(7),res.getString(8),res.getString(9)
                    ,res.getString(11),res.getString(12),res.getString(10)});
                } 
      
        jTable1.setModel(tb); 
          } catch (SQLException ex) {
           JOptionPane.showMessageDialog(this, ex);
        }   
    }
      public void total(){ 
tottal=0;
       for (int i = 0; i < jTable1.getRowCount()  ; i++) {  
    	tottal=tottal+Integer.valueOf(jTable1.getValueAt(i , 9).toString());
       } 
 jTextField1.setText(""+tottal);  
}
      public void tabelmodelpertanggal(){
       tb =new DefaultTableModel();
       tb.addColumn("No Faktu");
       tb.addColumn("Tanggal");
       tb.addColumn("Tempo"); 
       tb.addColumn("Nama Otlet");
       tb.addColumn("Nama Barang");
       tb.addColumn("Qty");
       tb.addColumn("Harga");
       tb.addColumn("Disc");
       tb.addColumn("Bonus");
       tb.addColumn("Subtotal");
       try {
           
   
         ResultSet res = coon.ambilData("select *from vpenjualan where tanggal >='"+sdf.format(jDateChooser1.getDate()) +"' and tanggal <='"+sdf.format(jDateChooser2.getDate())+"'");
        while (res.next()){
                    tb.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3)
                    ,res.getString(5),res.getString(7),res.getString(8),res.getString(9)
                    ,res.getString(11),res.getString(12),res.getString(10)});
                } 
      
        jTable1.setModel(tb); 
          } catch (SQLException ex) {
           JOptionPane.showMessageDialog(this, ex);
        }   
    }
}
