/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import Utility.autonumber;
import Utility.cetak;
import Utility.koneksi;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author User
 */
public class master_barang extends javax.swing.JFrame {
static DefaultTableModel tb; 

   static   koneksi coon=new koneksi();
 SimpleDateFormat tahun = new SimpleDateFormat("yy");
 SimpleDateFormat bulan = new SimpleDateFormat("MM");
    autonumber auto=new autonumber();
   NumberFormat kurensi = NumberFormat.getInstance(); 
   DecimalFormat df=new DecimalFormat("#.##");
    cetak Cetak=new cetak();
 int tottal;
 boolean tab ;
 static mytablecellrender render=new mytablecellrender();
 boolean status;
 
    /**
     * Creates new form master_barang
     */
    public master_barang() {
        initComponents(); 
        tabelmodel();
        setLocationRelativeTo(this);
      panelharga.setVisible(false);
               jTable1.setDefaultRenderer(Object.class,new mytablecellrender());  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtcari = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        txtmodal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtjual = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtsatuan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtkode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtstock = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtpercen = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        panelharga = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        hargabaru = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel6.setText("Cari");

        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcariKeyReleased(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtmodal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmodalKeyReleased(evt);
            }
        });

        jLabel4.setText("Harga Jual");

        txtjual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtjualKeyReleased(evt);
            }
        });

        jLabel7.setText("Satuan");

        txtsatuan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsatuanKeyReleased(evt);
            }
        });

        jLabel1.setText("Kode");

        txtkode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtkodeKeyReleased(evt);
            }
        });

        jLabel2.setText("Nama");

        txtnama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnamaKeyReleased(evt);
            }
        });

        jLabel5.setText("Stok");

        jLabel3.setText("Harga Modal");

        txtstock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtstockKeyReleased(evt);
            }
        });

        jLabel8.setText("Percentase");

        jLabel9.setText("%");

        panelharga.setBackground(new java.awt.Color(255, 255, 153));

        jLabel10.setText("Perubahan Harga:");

        hargabaru.setText("-");

        javax.swing.GroupLayout panelhargaLayout = new javax.swing.GroupLayout(panelharga);
        panelharga.setLayout(panelhargaLayout);
        panelhargaLayout.setHorizontalGroup(
            panelhargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelhargaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelhargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hargabaru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        panelhargaLayout.setVerticalGroup(
            panelhargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelhargaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hargabaru)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmodal, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtkode, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtstock, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtjual, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtpercen, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(panelharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(txtjual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtkode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel8)
                    .addComponent(txtpercen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel2)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(txtsatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtstock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtmodal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Simpan");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton2KeyReleased(evt);
            }
        });

        jButton3.setText("Edit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Hapus");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
            if (txtkode.getText().equals("")||txtnama.getText().equals("")) {
        JOptionPane.showMessageDialog(this,"Data belum lengkap");
    }
    else{
coon.simpanData("update tblbarang	set "
                + " Nama ='"+txtnama.getText()+"', "
                + " satuan ='"+txtsatuan.getText()+"', "
                + " HargaModal= '"+txtmodal.getText()+"', "
                + " HargaJual= '"+txtjual.getText()+"', "
                + " qty = '"+txtstock.getText()+"'"
        + " where "
        
                + " kode ='"+txtkode.getText()+"'" 
        + ";");
                     coon.simpanData("delete from ubahharga where kode="+
	"'"+txtkode.getText()+"'");
        
        bersihaset();
        tabelmodel(); 
         }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
               coon.simpanData("delete from tblbarang where kode="+
	"'"+txtkode.getText()+"'");
        tabelmodel(); 
        bersihaset(); 
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int baris=jTable1.getSelectedRow();
txtkode.setText(jTable1.getValueAt(baris,0).toString());
txtnama.setText(jTable1.getValueAt(baris,1).toString());
txtsatuan.setText(jTable1.getValueAt(baris,2).toString());
txtmodal.setText(jTable1.getValueAt(baris,3).toString());
txtjual.setText(jTable1.getValueAt(baris,4).toString());
txtstock.setText(jTable1.getValueAt(baris,5).toString()); 
    double jual,modal,untung;
            float persen;
            jual=Integer.valueOf(txtjual.getText());
            modal=Integer.valueOf(txtmodal.getText());
            untung=jual-modal;
            persen=(float) (untung/modal)*100;
            
             txtpercen.setText(""+ df.format(persen) ); 
                   cek();
                
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyReleased
    if (txtcari.equals("")) {
        
    }
    else{
        cari(txtcari.getText());
    }
        
    }//GEN-LAST:event_txtcariKeyReleased

    private void txtmodalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmodalKeyReleased
        // TODO add your handling code here:
        if( !txtjual.getText().equals("")){
            int jual,modal,untung;
            float persen;
            jual=Integer.valueOf(txtjual.getText());
            modal=Integer.valueOf(txtmodal.getText());
            untung=jual-modal;
            persen=(untung/modal)*100;
            txtpercen.setText(""+ df.format(persen) );
             
        }
        else{
            
        }
         if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            txtjual.requestFocus();
        }
    }//GEN-LAST:event_txtmodalKeyReleased

    private void txtjualKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtjualKeyReleased
 if(!txtmodal.getText().equals("") ){
               double jual,modal,untung;
            float persen;
            jual=Integer.valueOf(txtjual.getText());
            modal=Integer.valueOf(txtmodal.getText());
            untung=jual-modal;
            persen=(float) (untung/modal)*100;
            
            txtpercen.setText(""+ df.format(persen) );
           
 }
        else{
         
        }
    if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            txtstock.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjualKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            
      bersihaset(); 
        tabelmodel(); 
               jTable1.setDefaultRenderer(Object.class,new mytablecellrender());  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtkodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtkodeKeyReleased
        // TODO add your handling code here:
  if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            txtnama.requestFocus();
        }
    }//GEN-LAST:event_txtkodeKeyReleased

    private void txtnamaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnamaKeyReleased
        // TODO add your handling code here:
          if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            txtsatuan.requestFocus();
        }
    }//GEN-LAST:event_txtnamaKeyReleased

    private void txtsatuanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsatuanKeyReleased
        // TODO add your handling code here:
          if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            txtmodal.requestFocus();
        }
    }//GEN-LAST:event_txtsatuanKeyReleased

    private void txtstockKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtstockKeyReleased
        // TODO add your handling code here:
           if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            jButton2.requestFocus();
        }
    }//GEN-LAST:event_txtstockKeyReleased

    private void jButton2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyReleased
        // TODO add your handling code here:
            if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
      
              simpan(); 
        }
    }//GEN-LAST:event_jButton2KeyReleased

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        simpan();
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(master_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(master_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(master_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(master_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new master_barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hargabaru;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTable1;
    private javax.swing.JPanel panelharga;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtjual;
    private javax.swing.JTextField txtkode;
    private javax.swing.JTextField txtmodal;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtpercen;
    private javax.swing.JTextField txtsatuan;
    private javax.swing.JTextField txtstock;
    // End of variables declaration//GEN-END:variables

    static class mytablecellrender extends DefaultTableCellRenderer{

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
         Component c= super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column); //To change body of generated methods, choose Tools | Templates.
                    if ( table.getModel().getValueAt(row, 6).equals("berubah")) { 
                   c.setBackground(  Color.red );  
                        }
                    else if (row==table.getSelectedRow()) {
                  c.setBackground(  Color.LIGHT_GRAY ); 
            }
                        else{
                            
                    c.setBackground(  table.getBackground() );
                        }
                    c.setForeground(Color.BLACK);
             return this;
        }
        
    }
    void simpan(){
        
              if (txtkode.getText().equals("")||txtnama.getText().equals("")) {
        JOptionPane.showMessageDialog(this,"Data belum lengkap");
    }
    else{
coon.simpanData("insert into tblbarang	values"
                + "	('"+txtkode.getText()+"'," 
                + "'"+txtnama.getText()+"',"
                + "'"+txtsatuan.getText()+"',"
                + "'"+txtmodal.getText()+"',"
                + "'"+txtjual.getText()+"',"
                + "'"+txtstock.getText()+"',"
                + " 'normal');");
                  
        bersihaset();
        tabelmodel(); 
         }
              txtkode.requestFocus();
    }
    public static void tabelmodel(){
       tb =new DefaultTableModel();
       tb.addColumn("Kode ");
       tb.addColumn("Nama");
       tb.addColumn("satuan");
       tb.addColumn("Harga Modal");
       tb.addColumn("Harga Jual");
       tb.addColumn("Stok");
       tb.addColumn("status"); 
       try {
           
   
         ResultSet res = coon.ambilData("select *from tblbarang");
        while (res.next()){
                    tb.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3)
                    ,res.getString(4),res.getString(5),res.getString(6),res.getString(7)});
                } 
      
        jTable1.setModel(tb); 
      
          } catch (SQLException ex) {
           JOptionPane.showMessageDialog(jTable1, ex);
        }   
    }
public void cari(String cari){ 
       tb =new DefaultTableModel();
     tb.addColumn("Kode ");
       tb.addColumn("Nama");
       tb.addColumn("satuan");
       tb.addColumn("Harga Modal");
       tb.addColumn("Harga Jual");
       tb.addColumn("Stok");
       tb.addColumn("status"); 
       try {
           
   
         ResultSet res = coon.ambilData("select *from tblbarang where kode  like '%"+cari+"%' or nama like '%"+cari+"%'");
        while (res.next()){
                   tb.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3)
                    ,res.getString(4),res.getString(5),res.getString(6),res.getString(7)});
                } 
      
        jTable1.setModel(tb); 
          } catch (SQLException ex) {
           JOptionPane.showMessageDialog(jTable1, ex);
        }   
    }
void bersihaset(){
	txtkode.setText("");
	txtnama.setText("");
	txtmodal.setText("");
	txtjual.setText("");
	txtsatuan.setText("");
	txtpercen.setText("");
	txtstock.setText(""); 
	 
}
public void Setkodeaset1(){
        try {          
     auto.SetAutoNumber("tblbarang","kode","BR-"); 
     txtkode.setText(auto.GetAutoNumber());    
        } catch (Exception e) {
       System.out.printf(null, e);
        }
  }
void cek(){
    
    try { 
        ResultSet res = coon.ambilData("select * from ubahharga where kode='"+txtkode.getText()+"'");
        
        
        if (res.next()) {
            panelharga.setVisible(true);
        hargabaru.setText(res.getString(2));
        }
        else{
            panelharga.setVisible(false);
        }
    } catch (SQLException ex) {
        Logger.getLogger(master_barang.class.getName()).log(Level.SEVERE, null, ex);
    }
}

}

