/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import Utility.KonversiAngka;
import Utility.autonumbertransaksi;
import Utility.cetak;
import Utility.koneksi;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Penjualan extends javax.swing.JFrame {
    String order;
String tempo;
DefaultTableModel tb; 
 Calendar cal=Calendar.getInstance();
      koneksi coon=new koneksi();
       SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
 SimpleDateFormat tahun = new SimpleDateFormat("yy");
 SimpleDateFormat bulan = new SimpleDateFormat("MM");
    autonumbertransaksi auto=new autonumbertransaksi();
    KonversiAngka konver;
   NumberFormat kurensi = NumberFormat.getInstance();

  cetak Cetak=new cetak();
Map<String, Object> param = new HashMap<String, Object>();
 int tottal;
   DecimalFormat df=new DecimalFormat("#.##");
 boolean tab;
    /**
     * Creates new form Penjualan
     */
    public Penjualan() {
        initComponents();
        jDateChooser1.setDate(new Date());
        jButton1.requestFocus();
        Setkodeaset();
        setLocationRelativeTo(this);
        tabelmodel(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtfaktur = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jmlhari = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtterbilang = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("No Faktur");

        txtfaktur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfakturKeyReleased(evt);
            }
        });

        jLabel2.setText("Tanggal");

        jLabel3.setText("Tanggal Tempo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(txtfaktur, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jmlhari, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(txtfaktur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jmlhari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setText("Kode Otlet");

        txtkdotlet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtkdotletKeyReleased(evt);
            }
        });

        jLabel5.setText("Alamat");

        jButton1.setText("...");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton1KeyReleased(evt);
            }
        });

        jLabel6.setText("Nama");

        txtnotelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnotelpActionPerformed(evt);
            }
        });

        jLabel7.setText("No Telp");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtkdotlet, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtnamaotlet, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnotelp, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtkdotlet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel5)
                    .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtnamaotlet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtnotelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setText("Kode Barang");

        txtkdbarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtkdbarangKeyReleased(evt);
            }
        });

        jLabel9.setText("Nama barang");

        jLabel10.setText("Harga");

        jLabel11.setText("Qty");

        txtqty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtqtyKeyReleased(evt);
            }
        });

        jButton2.setText("...");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton2KeyReleased(evt);
            }
        });

        jLabel14.setText("Diskon");

        txtdiskon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdiskonKeyReleased(evt);
            }
        });

        jLabel15.setText("Bonus");

        txtbonus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbonusKeyReleased(evt);
            }
        });

        jButton4.setText("+");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton4KeyReleased(evt);
            }
        });

        jButton5.setText("-");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel16.setText("Satuan");

        jLabel17.setText("Stock");

        jLabel18.setText("Persentase");

        jButton8.setText("Edit");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtkdbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtnamabarang, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtqty, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtdiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtbonus, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtsatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtstock, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtpersen, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(txtstock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jLabel14)
                    .addComponent(txtdiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jLabel8)
                    .addComponent(txtkdbarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18)
                    .addComponent(jLabel11)
                    .addComponent(txtqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpersen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtbonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5)
                    .addComponent(txtsatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtnamabarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel12.setText("Total");

        jLabel13.setText("Terbilang");

        jButton3.setText("Simpan");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton6.setText("Retur");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Cetak Faktur");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtterbilang)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtterbilang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnotelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnotelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnotelpActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         int diskon;
         String bonus;
         int status =0;
         for (int i = 0; i < jTable1.getRowCount()  ; i++) {
             if (txtkdbarang.getText().equals(jTable1.getValueAt(i, 0).toString())) {
                 JOptionPane.showMessageDialog(rootPane,"Barang Sudah Di input !!!");
                 status=1;
             }
             
        }
         if (status==1) {
            
        }
         else if (cekstock()) {
            
                 JOptionPane.showMessageDialog(rootPane,"Stock Barang TIdak Cukup !!!");
        }
         else{
         if (txtdiskon.getText().equals("")) {
            diskon=0;
        }
         else{
             
        diskon=((Integer.valueOf(txtharga.getText())*Integer.valueOf(txtqty.getText()))*Integer.valueOf(txtdiskon.getText()))/100;
         }
          if (txtbonus.getText().equals("")) {
            bonus="";
        }
         else{
             
       bonus="BNS "+txtbonus.getText();
         } 
          if (txtdiskon.getText().equals("")) {
                 tb.addRow(new Object[]{txtkdbarang.getText(),txtnamabarang.getText(),txtharga.getText()
                ,txtqty.getText(),bonus,txtsatuan.getText(),txtdiskon.getText(),(Integer.valueOf(txtharga.getText())*Integer.valueOf(txtqty.getText()))-diskon});
      
        }
          else{
             tb.addRow(new Object[]{txtkdbarang.getText(),txtnamabarang.getText(),txtharga.getText()
                ,txtqty.getText(),bonus,txtsatuan.getText(),txtdiskon.getText()+" %",(Integer.valueOf(txtharga.getText())*Integer.valueOf(txtqty.getText()))-diskon});
      
    }
       jTable1.setModel(tb);
        bersihaset();
 total();
         }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
 
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int baris=jTable1.getSelectedRow();
          if (baris<0) {
              JOptionPane.showMessageDialog(rootPane,"Pilih Data Yang Ingin Dihapus Terlebih Dahulu !!!");
        }
          else{
              
        tb.removeRow(baris);
              total();
          }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
            simpancetak();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtkdbarangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtkdbarangKeyReleased
        // TODO add your handling code here:
        if(!txtkdbarang.getText().equals("")){
            tampilBarang();
        }
    }//GEN-LAST:event_txtkdbarangKeyReleased

    private void txtfakturKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfakturKeyReleased
        // TODO add your handling code here:
tampilFaktur();
total();
    }//GEN-LAST:event_txtfakturKeyReleased

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTable1KeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
       /*int baris=jTable1.getSelectedRow();
txtkdbarang.setText(jTable1.getValueAt(baris,0).toString());
tampilBarang();
txtharga.setText(jTable1.getValueAt(baris,2).toString());
txtqty.setText(jTable1.getValueAt(baris,3).toString());
txtdiskon.setText(jTable1.getValueAt(baris,6).toString());
txtbonus.setText(jTable1.getValueAt(baris,4).toString().replace("Bns",""));*/
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            // TODO add your handling code here:
            ResultSet res = coon.ambilData("select * from notelp  ");
            
            
            if (res.next()) {
                param.put("telp",res.getString(1));
            }
            else{
                param.put("telp","-");
            }
            param.put("no_faktur", txtfaktur.getText());
            param.put("terbilang", txtterbilang.getText());
            File file = new File("D:/java/faktur/faktur.jrxml");
            Cetak.cetak(file, param);
            Setkodeaset();
            tabelmodel();
            bersih();
            } catch (SQLException ex) {
                     Logger.getLogger(Penjualan.class.getName()).log(Level.SEVERE, null, ex);
                 }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        retur();
           Setkodeaset();
        tabelmodel();
        bersih();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        // TODO add your handling code here:
       jTable1.addKeyListener(new KeyAdapter() {

            @Override
            public void keyPressed(KeyEvent e) {
                
            }

           @Override
           public void keyReleased(KeyEvent e) {
               if(e.getKeyCode()==KeyEvent.VK_ENTER){
                        int row=jTable1.getSelectedRow();
          int diskon;
         String bonus;
     
             
        diskon=(Integer.valueOf(jTable1.getValueAt(row , 2).toString())*Integer.valueOf(jTable1.getValueAt(row , 6).toString()))/100;
        diskon=Integer.valueOf(jTable1.getValueAt(row , 7).toString())-diskon;
        jTable1.setValueAt(diskon, row, 7);
                }
           }

           @Override
           public void keyTyped(KeyEvent e) {
               super.keyTyped(e); //To change body of generated methods, choose Tools | Templates.
           }
            
            
});
      
    }//GEN-LAST:event_jTable1KeyReleased

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        edit();
        total();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void txtkdotletKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtkdotletKeyReleased
        // TODO add your handling code here:
   if(!txtkdotlet.getText().equals("")){
            tampilotlet();
        }
    }//GEN-LAST:event_txtkdotletKeyReleased

    private void txtqtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtqtyKeyReleased
        // TODO add your handling code here:
  if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            txtdiskon.requestFocus();
        }
    }//GEN-LAST:event_txtqtyKeyReleased

    private void txtdiskonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdiskonKeyReleased
        // TODO add your handling code here:
          if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            txtbonus.requestFocus();
        }
    }//GEN-LAST:event_txtdiskonKeyReleased

    private void txtbonusKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbonusKeyReleased
        // TODO add your handling code here:
          if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
           jButton4.requestFocus();
        }
    }//GEN-LAST:event_txtbonusKeyReleased

    private void jButton4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton4KeyReleased
        // TODO add your handling code here:
           if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            int diskon;
         String bonus;
         int status =0;
         for (int i = 0; i < jTable1.getRowCount()  ; i++) {
             if (txtkdbarang.getText().equals(jTable1.getValueAt(i, 0).toString())) {
                 JOptionPane.showMessageDialog(rootPane,"Barang Sudah Di input !!!");
                 status=1;
             }
             
        }
         if (status==1) {
            
        }
         else if (cekstock()) {
            
                 JOptionPane.showMessageDialog(rootPane,"Stock Barang TIdak Cukup !!!");
        }
         else{
         if (txtdiskon.getText().equals("")) {
            diskon=0;
        }
         else{
             
        diskon=((Integer.valueOf(txtharga.getText())*Integer.valueOf(txtqty.getText()))*Integer.valueOf(txtdiskon.getText()))/100;
         }
          if (txtbonus.getText().equals("")) {
            bonus="";
        }
         else{
             
       bonus="BNS "+txtbonus.getText();
         } 
          if (txtdiskon.getText().equals("")) {
                 tb.addRow(new Object[]{txtkdbarang.getText(),txtnamabarang.getText(),txtharga.getText()
                ,txtqty.getText(),bonus,txtsatuan.getText(),txtdiskon.getText(),(Integer.valueOf(txtharga.getText())*Integer.valueOf(txtqty.getText()))-diskon});
      
        }
          else{
             tb.addRow(new Object[]{txtkdbarang.getText(),txtnamabarang.getText(),txtharga.getText()
                ,txtqty.getText(),bonus,txtsatuan.getText(),txtdiskon.getText()+" %",(Integer.valueOf(txtharga.getText())*Integer.valueOf(txtqty.getText()))-diskon});
      
    }
       jTable1.setModel(tb);
        bersihaset();
 total();
         }
         jButton2.requestFocus();
        }
           
    }//GEN-LAST:event_jButton4KeyReleased

    private void jButton2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyReleased
        // TODO add your handling code here:
         if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
       new cariBarangjual().setVisible(true); 
        }
         else if (evt.isControlDown()&& evt.getKeyCode()== KeyEvent.VK_P) { 
                 simpancetak();
        }
    }//GEN-LAST:event_jButton2KeyReleased

    private void jButton1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyReleased
        // TODO add your handling code here:
          if (evt.getKeyCode()==KeyEvent.VK_ENTER) { 
                  new cariotlet().setVisible(true);
        }
          
    }//GEN-LAST:event_jButton1KeyReleased

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
               new cariBarangjual().setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
                new cariotlet().setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Penjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButton1;
    public static javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jmlhari;
    public static final javax.swing.JTextField txtalamat = new javax.swing.JTextField();
    public static final javax.swing.JTextField txtbonus = new javax.swing.JTextField();
    public static final javax.swing.JTextField txtdiskon = new javax.swing.JTextField();
    private javax.swing.JTextField txtfaktur;
    public static final javax.swing.JTextField txtharga = new javax.swing.JTextField();
    public static final javax.swing.JTextField txtkdbarang = new javax.swing.JTextField();
    public static final javax.swing.JTextField txtkdotlet = new javax.swing.JTextField();
    public static final javax.swing.JTextField txtnamabarang = new javax.swing.JTextField();
    public static final javax.swing.JTextField txtnamaotlet = new javax.swing.JTextField();
    public static final javax.swing.JTextField txtnotelp = new javax.swing.JTextField();
    public static final javax.swing.JTextField txtpersen = new javax.swing.JTextField();
    public static final javax.swing.JTextField txtqty = new javax.swing.JTextField();
    public static final javax.swing.JTextField txtsatuan = new javax.swing.JTextField();
    public static final javax.swing.JTextField txtstock = new javax.swing.JTextField();
    private javax.swing.JTextField txtterbilang;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables

    public void tabelmodel(){
       tb =new DefaultTableModel();
       tb.addColumn("Kode Barang ");
       tb.addColumn("Nama Barang ");
       tb.addColumn("Harga Satuan");
       tb.addColumn("Qty");
       tb.addColumn("Bonus");
       tb.addColumn("Satuan");
       tb.addColumn("Disc");
       tb.addColumn("Total");
        jTable1.setModel(tb);
       
    }
    void bersihaset(){
	txtkdbarang.setText("");
	txtnamabarang.setText("");
	txtqty.setText("");
	txtdiskon.setText("");
	txtsatuan.setText("");
	txtbonus.setText(""); 
	txtharga.setText(""); 
	txtstock.setText(""); 
	txtpersen.setText(""); 
	 }
     void bersih(){
	txtkdotlet.setText("");
	txtnamaotlet.setText("");
	txtalamat.setText("");
	txtnotelp.setText("");
	txtterbilang.setText("");
	txttotal.setText(""); 
	jmlhari.setText(""); 
        
	 }
    public void total(){ 
tottal=0;
       for (int i = 0; i < jTable1.getRowCount()  ; i++) {  
    	tottal=tottal+Integer.valueOf(jTable1.getValueAt(i , 7).toString());
       } 
 txttotal.setText(""+tottal); 
 konver=new KonversiAngka(tottal);
 txtterbilang.setText(konver.getText());
}
   void simpan2(){
        if (txtfaktur.getText().equals("")||txtkdotlet.getText().equals("")||jmlhari.getText().equals("")) {
        JOptionPane.showMessageDialog(this,"Data belum lengkap Lihat Tanggal Tempo Atau Data Otlet");
    }
    else{
            for (int i = 0; i < jTable1.getRowCount()  ; i++) {  
                  if(jTable1.getValueAt(i , 6).toString().equals("")){ 
                        coon.simpanData("insert into tbl_detilpenjualan	values"
                + "	('"+txtfaktur.getText()+"'," 
                + "'"+jTable1.getValueAt(i , 0).toString()+"',"
                + "'"+jTable1.getValueAt(i , 3).toString()+"',"
                + "'"+jTable1.getValueAt(i , 2).toString()+"',"
                + "'"+jTable1.getValueAt(i , 7).toString()+"',"
                + "'0',"
                + "'"+jTable1.getValueAt(i , 4).toString().replace("BNS", "Bns")+"');");    
                 
                        coon.simpanData("update db_faktur.tblbarang "
                + "set" 
                + " qty =qty-'"+jTable1.getValueAt(i , 4).toString().replace("BNS", "")+"' "
             
                + " where kode ='"+jTable1.getValueAt(i , 0).toString()+"' ;");
                        }
                 else  if(jTable1.getValueAt(i , 4).toString().equals("")){ 
                    coon.simpanData("insert into tbl_detilpenjualan	values"
                + "	('"+txtfaktur.getText()+"'," 
                + "'"+jTable1.getValueAt(i , 0).toString()+"',"
                + "'"+jTable1.getValueAt(i , 3).toString()+"',"
                + "'"+jTable1.getValueAt(i , 2).toString()+"',"
                + "'"+jTable1.getValueAt(i , 7).toString()+"',"
                + "'"+jTable1.getValueAt(i , 6).toString().replace("%", "")+"',"
                + "'');");     
                        }
                 else{ 
                coon.simpanData("insert into tbl_detilpenjualan	values"
                + "	('"+txtfaktur.getText()+"'," 
                + "'"+jTable1.getValueAt(i , 0).toString()+"',"
                + "'"+jTable1.getValueAt(i , 3).toString()+"',"
                + "'"+jTable1.getValueAt(i , 2).toString()+"',"
                + "'"+jTable1.getValueAt(i , 7).toString()+"',"
                + "'"+jTable1.getValueAt(i , 6).toString().replace("%", "")+"',"
                + "'"+jTable1.getValueAt(i , 4).toString().replace("BNS", "Bns")+"');");
             
                coon.simpanData("update db_faktur.tblbarang "
                + "set" 
                + " qty =qty-'"+jTable1.getValueAt(i , 4).toString().replace("BNS", "")+"' "
             
                + " where kode ='"+jTable1.getValueAt(i , 0).toString()+"' ;");
                 }
        }
            }
   
       

                  
   }
     void simpan(){
   tambaTgL();
coon.simpanData("insert into tbl_penjualan	values"
                + "	('"+txtfaktur.getText()+"'," 
                + "'"+sdf.format(jDateChooser1.getDate())+"',"
                + "'"+sdf.format(cal.getTime())+"',"
                + "'"+txtkdotlet.getText()+"',"
                + "'"+txttotal.getText()+"');");
        
                  
   }
       
    public void Setkodeaset(){
        try {          
         String kode="/"+bulan.format(jDateChooser1.getDate())+"/"+tahun.format(jDateChooser1.getDate());
         
      auto.SetAutoNumber("tbl_penjualan","NoFaktur",kode); 
     txtfaktur.setText(auto.GetAutoNumber());    
        } catch (Exception e) {
       System.out.printf(null, e);
        }
  }
   void tambaTgL(){
             int hari=Integer.valueOf(jmlhari.getText());
        
         cal.setTime(jDateChooser1.getDate());
         cal.add(Calendar.DATE, hari); 
         
    }
   void tampilotlet(){
        try {
            ResultSet res = coon.ambilData("select *from tbl_otlet where kode='"+txtkdotlet.getText()+"'");
            if(res.next()){
                txtnamaotlet.setText(res.getString(2));
                txtalamat.setText(res.getString(3));
                txtnotelp.setText(res.getString(4));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Penjualan.class.getName()).log(Level.SEVERE, null, ex);
        }
   }
   
   void tampilBarang(){
    try {
        ResultSet res = coon.ambilData("select *from tblbarang where kode='"+txtkdbarang.getText()+"'");
        if(res.next()){
        txtkdbarang.setText(res.getString(1));
        txtnamabarang.setText(res.getString(2));
        txtsatuan.setText(res.getString(3));
        txtharga.setText(res.getString(5));
        txtstock.setText(res.getString(6));
        double jual,modal,untung;
        float persen;
        jual=Integer.valueOf(res.getString(5));
        modal=Integer.valueOf(res.getString(4));
        untung=jual-modal;
        persen=(float) (untung/modal)*100;
        Penjualan.txtpersen.setText(""+df.format(persen));
        }
        else{
            txtnamabarang.setText("");
	txtqty.setText("");
	txtdiskon.setText("");
	txtsatuan.setText("");
	txtbonus.setText(""); 
	txtharga.setText(""); 
	txtstock.setText(""); 
	txtpersen.setText(""); 
        }
    } catch (SQLException ex) {
       Logger.getLogger(Penjualan.class.getName()).log(Level.SEVERE, null, ex);
    }
}
   void tampilFaktur(){
       bersih();
       bersihaset();
       tabelmodel();
    try {
        ResultSet res = coon.ambilData("select *from vcetak where Nofaktur='"+txtfaktur.getText()+"'");
       
       
           while (res.next()){
                 SimpleDateFormat FormatTanggal = new SimpleDateFormat("dd MMMM yyyy");
      order = FormatTanggal.format(res.getDate(2)); 
     tempo = FormatTanggal.format(res.getDate(3));
      DateFormat format = new SimpleDateFormat("dd MMMM yyyy");
    Date tanggalpinjam = format.parse(order);
    Date tanggalkembali = format.parse(tempo);
    long tanggalpinjam1 = tanggalpinjam.getTime();
    long tanggalkembali1 = tanggalkembali.getTime();
    long diff = tanggalkembali1 - tanggalpinjam1;
    long lama = diff / (24 * 60 * 60 * 1000);
    jmlhari.setText(""+lama);
                jDateChooser1.setDate(res.getDate(2));
        txtkdotlet.setText(res.getString(4));
        txtnamaotlet.setText(res.getString(5));
        txtalamat.setText(res.getString(6));
        txtnotelp.setText(res.getString(7)); 
                    tb.addRow(new Object[]{res.getString(9),res.getString(10),res.getString(13)
                    ,res.getString(12),res.getString(16),res.getString(11),res.getString(15),res.getString(14)});
                } 
         
       
    } catch (SQLException ex) {
       Logger.getLogger(Penjualan.class.getName()).log(Level.SEVERE, null, ex);
    }   catch (ParseException ex) {
            Logger.getLogger(Penjualan.class.getName()).log(Level.SEVERE, null, ex);
        }
}
   void retur(){
          for (int i = 0; i < jTable1.getRowCount()  ; i++) {  
              try {
                  int qtyretur,qtyjual,selisih;
                  
                  ResultSet res = coon.ambilData("select * from tbl_detilpenjualan where Nofaktur='"+txtfaktur.getText()+"' and KodeBarang='"
                          +jTable1.getValueAt(i , 0).toString()+"'" );
                  res.next(); 
                        qtyjual=res.getInt(3);
                        qtyretur=Integer.valueOf(jTable1.getValueAt(i , 3).toString());
                        selisih=qtyjual-qtyretur; 
                    coon.simpanData("update tblbarang  set "
                + "qty = qty+"+selisih+""  
                + " where " 
                + "Kode  = '"+jTable1.getValueAt(i , 0).toString()+"'");
                    
                       coon.simpanData("update tbl_penjualan  set "
                + "Total = '"+txttotal.getText()+"'"  
                + " where " 
                + "Nofaktur  = '"+txtfaktur.getText()+"'");
                       
                          coon.simpanData("update tbl_detilpenjualan  set "
                + "qty = '"+jTable1.getValueAt(i , 3).toString()+"'," 
                + "subtotal = '"+jTable1.getValueAt(i , 7).toString()+"' "
                + " where "
                + "Nofaktur = '"+txtfaktur.getText()+"' and "
                + "KodeBarang = '"+jTable1.getValueAt(i , 0).toString()+"'");
                          
                    
                 
              } catch (SQLException ex) {
                  Logger.getLogger(Penjualan.class.getName()).log(Level.SEVERE, null, ex);
              }
        
          }
   }
 
   void edit(){
        for (int i = 0; i < jTable1.getRowCount()  ; i++) { 
          int diskon,sub;
         String bonus;
     
            if (jTable1.getValueAt(i , 6).toString().equals("")) {
                 sub=(Integer.valueOf(jTable1.getValueAt(i , 2).toString())*Integer.valueOf(jTable1.getValueAt(i , 3).toString()));
            }
            else{
        diskon=((Integer.valueOf(jTable1.getValueAt(i , 2).toString())*Integer.valueOf(jTable1.getValueAt(i , 3).toString()))*Integer.valueOf(jTable1.getValueAt(i , 6).toString()))/100;
        sub=(Integer.valueOf(jTable1.getValueAt(i , 2).toString())*Integer.valueOf(jTable1.getValueAt(i , 3).toString()))-diskon;
       }
            jTable1.setValueAt(sub, i, 7);
            
        }
   }
   boolean cekstock(){
       boolean e;
       int a,b,c;
       a=Integer.valueOf(txtqty.getText());
       if (txtbonus.getText().equals("")) {
           b=0;
       }else{
       b=Integer.valueOf(txtbonus.getText());
       }
       c=Integer.valueOf(txtstock.getText());
       if ((a+b)>c) {
           e=true;
       }
       else{
           e=false;
       }
        return e;
      
   }
        void simpancetak(){
             if (txtfaktur.getText().equals("")||txtkdotlet.getText().equals("")||jmlhari.getText().equals("")) {
        JOptionPane.showMessageDialog(this,"Data belum lengkap Lihat Tanggal Tempo Atau Data Otlet");
    }
    else{
                 try {
                     simpan();
                     simpan2();
                     ResultSet res = coon.ambilData("select * from notelp  ");
                     
                     
                     if (res.next()) {
                         param.put("telp",res.getString(1));
                     }
                     else{
                         param.put("telp","-");
                     } 
                     param.put("no_faktur", txtfaktur.getText());
                     param.put("terbilang", txtterbilang.getText());
                      File file = new File("D:/java/faktur/faktur.jrxml");
                int konf= JOptionPane.showConfirmDialog(null,"Apakah laporan Ingin Langsung Di Cetak ?","Konfirmasi",
                             JOptionPane.YES_NO_OPTION);
                
                   if(konf==JOptionPane.YES_OPTION){
                          Cetak.cetaklangsung(file, param);
                   }
                   else{
                       Cetak.cetak(file, param);
                   }
                                        Setkodeaset();
                     tabelmodel();
                     bersih();} catch (SQLException ex) {
                     Logger.getLogger(Penjualan.class.getName()).log(Level.SEVERE, null, ex);
                 }
             }
        }   
}
